spring:
  application:
    name: swaggergenerator
swagger:
  output-dir: C:\DevEnvironment\src\java\monitor-workspace\swagger
services:
  list:
    - name: simf
      controllersPath: C:/DevEnvironment/src/java/bm-workspace/bm-simf/api-simf/src/main/java
      beansPath: C:/DevEnvironment/src/java/bm-workspace/bm-simf/ws-simf/src/main/java
      basePackage: com.mercantilbanco.osba
      basePath: /simf
    - name: security
      controllersPath: C:/DevEnvironment/src/java/bm-workspace/bm-security/api-security/src/main/java
      beansPath: C:/DevEnvironment/src/java/bm-workspace/bm-security/ws-security/src/main/java
      basePackage: com.mercantilbanco.osba
      basePath: /security
    - name: tarjeta
      controllersPath: C:/DevEnvironment/src/java/bm-workspace/bm-tarjeta/api-tarjeta/src/main/java
      beansPath: C:/DevEnvironment/src/java/bm-workspace/bm-tarjeta/ws-tarjeta/src/main/java
      basePackage: com.mercantilbanco.osba
      basePath: /tarjeta
    - name: inversiones
      controllersPath: C:\DevEnvironment\src\java\bm-workspace\bm-inversiones\api-inversiones\src\main\java
      beansPath: C:\DevEnvironment\src\java\bm-workspace\bm-inversiones\ws-inversiones\src\main\java
      basePackage: com.mercantilbanco.osba
      basePath: /inversiones
    - name: persona
      controllersPath: C:\DevEnvironment\src\java\bm-workspace\bm-persona\api-persona\src\main\java
      beansPath: C:\DevEnvironment\src\java\bm-workspace\bm-persona\ws-persona\src\main\java
      basePackage: com.mercantilbanco.osba
      basePath: /persona
    - name: notifications
      controllersPath: C:\DevEnvironment\src\java\bm-workspace\bm-notifications\api-notifications\src\main\java
      beansPath: C:\DevEnvironment\src\java\bm-workspace\bm-notifications\db-notifications\src\main\java\com\mercantilbanco\osba\beans
      basePackage: com.mercantilbanco.osba
      basePath: /notifications
    - name: mia
      controllersPath: C:\DevEnvironment\src\java\bm-workspace\bm-mia\api-mia\src\main\java
      beansPath: C:\DevEnvironment\src\java\bm-workspace\bm-mia\ws-mia\src\main\java
      basePackage: com.mercantilbanco.osba
      basePath: /mia